### ISSUE TITLE
way to repair pushbullet.errors.InvalidKeyError

### ISSUE THREAD

**Issue by tbates** [r-darwish/pushbullet-cli#14]
I get an InvalidLeyError. The ~/.pushbulletkey file looks OK (I had to manually edit as the first time using the echo "hello"| pb example, "hello" got saved into this file...

But now with just 1-line containing my key, the error still occurs. might be handy to add some trouble shooting advice rather than the traceback in this case?

me:~ tim$ pb test
Traceback (most recent call last):
  File "/usr/local/bin/pb", line 9, in <module>
    load_entry_point('Pushbullet-CLI==0.1', 'console_scripts', 'pb')()
  File "build/bdist.macosx-10.10-intel/egg/pushbullet_cli/app.py", line 111, in main
  File "build/bdist.macosx-10.10-intel/egg/pushbullet/pushbullet.py", line 29, in __init__
  File "build/bdist.macosx-10.10-intel/egg/pushbullet/pushbullet.py", line 267, in refresh
  File "build/bdist.macosx-10.10-intel/egg/pushbullet/pushbullet.py", line 42, in _load_devices
  File "build/bdist.macosx-10.10-intel/egg/pushbullet/pushbullet.py", line 35, in _get_data
pushbullet.errors.InvalidKeyError
me:~ tim$

**Comment by t4exanadu** [comment]
I'm seeing a similar error, and I know my key is correct because I just set up pushbullet-cli on this computer. I just tried to set it up on an older distro (Peppermint 3), and running `pb` results in:

/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Traceback (most recent call last):
  File "/usr/local/bin/pb", line 9, in <module>
    load_entry_point('Pushbullet-CLI==0.1', 'console_scripts', 'pb')()
  File "/usr/local/lib/python2.7/dist-packages/Pushbullet_CLI-0.1-py2.7.egg/pushbullet_cli/app.py", line 111, in main
    pb = PushBullet(api_key)
  File "/usr/local/lib/python2.7/dist-packages/pushbullet.py-0.8.1-py2.7.egg/pushbullet/pushbullet.py", line 29, in __init__
    self.refresh()
  File "/usr/local/lib/python2.7/dist-packages/pushbullet.py-0.8.1-py2.7.egg/pushbullet/pushbullet.py", line 267, in refresh
    self._load_devices()
  File "/usr/local/lib/python2.7/dist-packages/pushbullet.py-0.8.1-py2.7.egg/pushbullet/pushbullet.py", line 42, in _load_devices
    resp_dict = self._get_data(self.DEVICES_URL)
  File "/usr/local/lib/python2.7/dist-packages/pushbullet.py-0.8.1-py2.7.egg/pushbullet/pushbullet.py", line 35, in _get_data
    raise InvalidKeyError()
pushbullet.errors.InvalidKeyError

**Comment by r-darwish** [comment]
Please check if 27ee63bf8162b0a458fbda4b2f554446406465f1 solves this issue

**Comment by t4exanadu** [comment]
@r-darwish Yes. that solves the issue for me. Thanks.
