### ISSUE TITLE
pushing file: not JSON serializable

### ISSUE THREAD

**Issue by JurnD** [r-darwish/pushbullet-cli#17]
Hi,

If I try to send a file ($ pb -a test) I get the following error:

Traceback (most recent call last):
  File "/usr/bin/pb", line 9, in <module>
    load_entry_point('pushbullet-cli==0.1', 'console_scripts', 'pb')()
  File "/usr/lib/python3.4/site-packages/pushbullet_cli-0.1-py3.4.egg/pushbullet_cli/app.py", line 144, in main
  File "/usr/lib/python3.4/site-packages/pushbullet_cli-0.1-py3.4.egg/pushbullet_cli/app.py", line 81, in _push
  File "/usr/lib/python3.4/site-packages/pushbullet.py-0.8.1-py3.4.egg/pushbullet/pushbullet.py", line 190, in upload_file
  File "/usr/lib/python3.4/json/__init__.py", line 230, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.4/json/encoder.py", line 192, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.4/json/encoder.py", line 250, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.4/json/encoder.py", line 173, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: b'text/plain' is not JSON serializable

I found this:
http://stackoverflow.com/questions/25849850/weird-typeerror-from-json-dumps

Thank you very much for this nice client.

Jurn

**Comment by r-darwish** [comment]
Hi,

Thanks for reporting. This issue appears to effect the pushbullet.py library as well. I opened a pull request for them:

https://github.com/randomchars/pushbullet.py/pull/45
