### ISSUE TITLE
Error when trying to push file

### ISSUE THREAD

**Issue by vikeri** [r-darwish/pushbullet-cli#21]
I get the following error when I try to push a file:
```
Traceback (most recent call last):
  File "/usr/local/bin/pb", line 9, in <module>
    load_entry_point('pushbullet-cli==0.6.0', 'console_scripts', 'pb')()
  File "/usr/local/lib/python2.7/site-packages/click-5.1-py2.7.egg/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click-5.1-py2.7.egg/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click-5.1-py2.7.egg/click/core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click-5.1-py2.7.egg/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click-5.1-py2.7.egg/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "build/bdist.macosx-10.11-x86_64/egg/pushbullet_cli/app.py", line 159, in push
  File "build/bdist.macosx-10.11-x86_64/egg/pushbullet_cli/app.py", line 65, in _push
  File "build/bdist.macosx-10.11-x86_64/egg/pushbullet/pushbullet.py", line 185, in upload_file
  File "build/bdist.macosx-10.11-x86_64/egg/pushbullet_cli/app.py", line 17, in wrapper
AttributeError: 'NoneType' object has no attribute 'decode'
```

**Comment by r-darwish** [comment]
I checked it with Python 2.7 in OS X 10.11 and it seems to work. Could you please give more details like the exact command that you ran or more information about the file (Is it large? Does its name contain non-English characters?)

**Comment by vikeri** [comment]
Hmm, it was an executable (no extension). I also tried with a markdown file that failed as well. But a txt file worked.

**Comment by r-darwish** [comment]
Please check if 517e092c04bc70782ac1b415efe09b133bd6aa16 solves your issue

**Comment by vikeri** [comment]
Worked! Thx! Btw, a short install instruction for us non-pythonists could be useful in the Readme. I had to look around a little before understanding how to install it. And it wont install with Mac's preinstalled Python, I had to `brew install python`.

**Comment by r-darwish** [comment]
I uploaded version 0.6.1 to PyPi which contains this fix, so you can stop using the develop branch

**Comment by vikeri** [comment]
Great!
