### ISSUE TITLE
Issue with formatting foreign characters

### ISSUE THREAD

**Issue by vikeri** [r-darwish/pushbullet-cli#25]
Hi,

When I do `pb list-devices` I get the following error:

````
Traceback (most recent call last):
  File "/usr/local/bin/pb", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pushbullet_cli/app.py", line 97, in list_devices
    print("{0}. {1}".format(i, device.nickname))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe4' in position 15: ordinal not in range(128)
````

And I guess it is related to the fact that i have the Swedish **Ä** in one device name.

**Comment by r-darwish** [comment]
Can you please tell me the output of `locale`?

**Comment by vikeri** [comment]
Wow, a response within the minute. Impressed!
````
LANG="sv_SE.UTF-8"
LC_COLLATE="sv_SE.UTF-8"
LC_CTYPE="sv_SE.UTF-8"
LC_MESSAGES="sv_SE.UTF-8"
LC_MONETARY="sv_SE.UTF-8"
LC_NUMERIC="sv_SE.UTF-8"
LC_TIME="sv_SE.UTF-8"
LC_ALL=
````

**Comment by r-darwish** [comment]
Thanks :)

locale seems to be fine. I'll have to investigate this

**Comment by r-darwish** [comment]
c8f2815 should fix this. I just uploaded a new version to PyPi (0.7.1) so there's no need for you to clone this repository. Please update and tell me if it's working

**Comment by vikeri** [comment]
Yes it is fixed! Great work!
